## apt-install.sh
## Mac Radigan

apt install openssh-server -y
apt install vim -y
apt install vim-gnome -y
apt install emacs -y
apt install zsh -y
apt install rlwrap -y
apt install screen -y
apt install tmux -y
apt install rxvt-unicode -y
apt install xfonts-terminus -y
apt install console-terminus -y
apt install git -y
apt install i3 -y
apt install stumpwm -y
apt install elinks -y
apt install lynx -y
apt install links -y
apt install xclip -y
apt install gambc -y
apt install chicken-bin -y
apt install guile-2.0 -y
apt install guile-2.0-dev -y
apt install mit-scheme -y
apt install clisp -y
apt install scbl -y
apt install ranger -y
apt install csound -y
apt install snd -y
apt install jack2 -y
apt install sonic -y
apt install chuck -y
apt install sox -y
apt install eog -y
apt install lilypond -y
apt install imagemagick -y
apt install octave -y
apt install liboctave-dev -y
apt install gnuplot -y
apt install graphviz -y
apt install wmctrl -y
apt install kate -y
apt install rcconf -y
apt install conky -y
apt install dtrx -y
apt install bison -y
apt install flex -y
apt install cowsay -y
apt install xpdf -y
apt install texlive-latex-extra -y
apt install texlive-science -y
apt install texlive-full -y
apt install python-pygments -y
apt install ipython -y
apt install python-numpy -y
apt install python-matplotlib -y
apt install python-pip -y
apt install python3-pip -y
apt install cython -y
apt install htop -y
apt install ikarus -y
apt install root-system -y
apt install sbcl -y
apt install clisp -y
apt install axiom -y
apt install cmake -y
apt install ecl -y
apt install libboost-all-dev -y
apt install gnuradio -y
apt install liblapack-devel -y
apt install jack -y
apt install julia -y
apt install pdl -y
apt install inkscape -y
apt install blender -y
apt install libeigen3-dev -y
apt install xmonad -y
apt install llvm-dev -y
apt install hovercraft -y
apt install kvm -y
apt install tcl-dev -y
apt install libzmq5-dev -y
apt install ocaml -y
apt install groovy -y
apt install scala -y
apt install expect -y
apt install spark -y
apt install finch -y
apt install yacas -y
apt install maximus -y
apt install ikvm -y
apt install mutt/xenial -y
apt install ruby -y
apt install ruby-dev -y
apt install libz-dev -y
apt install libicu-dev -y
apt install build-essential -y
apt install python3-dev -y
apt install enscript -y
apt install autoconf -y
apt install automake -y
apt install libopenblas-base -y
apt install libopenblas-dev -y
apt install cscope -y
apt install global -y
apt install default-jdk -y
apt install racket -y
apt install ack-grep -y
apt install mdk -y
apt install torque-server -y
apt install torque-client -y
apt install torque-mom -y
apt install torque-pam -y
apt install docker -y

add-apt-repository ppa:atareao/atareao
apt install touchpad-indicator -y

## *EOF*
